export const GET_ALERTS_REQUEST = "GET_ALERTS_REQUEST"
export const GET_ALERTS_SUCCESS = "GET_ALERTS_SUCCESS"
export const GET_ALERTS_FAILURE = "GET_ALERTS_FAILURE"

export const GET_ALERT_DETAILS_REQUEST = "GET_ALERT_DETAILS_REQUEST"
export const GET_ALERT_DETAILS_SUCCESS = "GET_ALERT_DETAILS_SUCCESS"
export const GET_ALERT_DETAILS_FAILURE = "GET_ALERT_DETAILS_FAILURE"
